# Enable mouse emulation.
CONFIG_ZMK_POINTING=y

# Tweak Bluetooth connection settings
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"

# Enable the WS2812 layer indicator widget
# CONFIG_WS2812_WIDGET=y
# CONFIG_WS2812_WIDGET_SHOW_LAYER_COLORS=y
# Enable LED strip support
# CONFIG_LED_STRIP=y
# CONFIG_WS2812_STRIP=y

# Layer Colors at 25% Brightness (Hex format: RRGGBB using 40 for max active value)
# CONFIG_WS2812_WIDGET_LAYER_0_COLOR=0x000000 # Base Layer (Off)
# CONFIG_WS2812_WIDGET_LAYER_1_COLOR=0x404000 # Layer 1 (25% Yellow)
# CONFIG_WS2812_WIDGET_LAYER_2_COLOR=0x004000 # Layer 2 (25% Green)
# CONFIG_WS2812_WIDGET_LAYER_3_COLOR=0x000040 # Layer 3 (25% Blue)
# CONFIG_WS2812_WIDGET_LAYER_4_COLOR=0x400000 # Layer 4 (25% Red)
# CONFIG_WS2812_WIDGET_LAYER_5_COLOR=0x400040 # Layer 5 (25% Purple)
# CONFIG_WS2812_WIDGET_LAYER_6_COLOR=0x004040 # Layer 6 (25% Cyan)
# CONFIG_WS2812_WIDGET_LAYER_7_COLOR=0x404040 # Layer 7 (25% White)
