manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    ## enable rgb underglow based on active layer
    - name: gohanda11
      url-base: https://github.com/gohanda11 
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-ws2812-driver
      remote: gohanda11
      revision: main
  self:
    path: config
